# - Try to find the CryptSetup libraries
# Once done this will define
#
#  CRYPTSETUP_FOUND - system has pam
#  CRYPTSETUP_INCLUDE_DIR - the pam include directory
#  CRYPTSETUP_LIBRARIES - libpam library

if (CRYPTSETUP_INCLUDE_DIR AND CRYPTSETUP_LIBRARY)
	set(CRYPTSETUP_FIND_QUIETLY TRUE)
endif (CRYPTSETUP_INCLUDE_DIR AND CRYPTSETUP_LIBRARY)

find_path(CRYPTSETUP_INCLUDE_DIR NAMES libcryptsetup.h)
find_library(CRYPTSETUP_LIBRARY cryptsetup)

if (CRYPTSETUP_INCLUDE_DIR AND CRYPTSETUP_LIBRARY)
	set(CRYPTSETUP_FOUND TRUE)
    set(CRYPTSETUP_LIBRARIES ${CRYPTSETUP_LIBRARY})
endif (CRYPTSETUP_INCLUDE_DIR AND CRYPTSETUP_LIBRARY)

if (CRYPTSETUP_FOUND)
	if (NOT CRYPTSETUP_FIND_QUIETLY)
		message(STATUS "Found CRYPTSETUP: ${CRYPTSETUP_LIBRARIES}")
	endif (NOT CRYPTSETUP_FIND_QUIETLY)
else (CRYPTSETUP_FOUND)
	if (CRYPTSETUP_FIND_REQUIRED)
		message(FATAL_ERROR "CRYPTSETUP was not found")
	endif(CRYPTSETUP_FIND_REQUIRED)
endif (CRYPTSETUP_FOUND)

mark_as_advanced(PAM_INCLUDE_DIR PAM_LIBRARY DL_LIBRARY)

